// <auto-generated />
using System;
using AddressBookAssessment.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBookAssessment.Services.Data.Migrations
{
    [DbContext(typeof(AddressBookAssessmentContext))]
    partial class AddressBookAssessmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressBookAssessment.Core.AddressBook.AddressBookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AddressBookEntries", (string)null);
                });

            modelBuilder.Entity("AddressBookAssessment.Core.AddressBook.AddressBookEntry", b =>
                {
                    b.OwnsOne("AddressBookAssessment.Core.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AddressBookEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("CountryAbbreviation")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Line3")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("StateAbbreviation")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("AddressBookEntryId");

                            b1.ToTable("AddressBookEntries");

                            b1.WithOwner()
                                .HasForeignKey("AddressBookEntryId");
                        });

                    b.OwnsMany("AddressBookAssessment.Core.AddressBook.AddressBookContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("AddressBookEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CellPhoneNumber")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("OfficePhoneNumber")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("AddressBookEntryId", "Id");

                            b1.ToTable("AddressBookContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AddressBookEntryId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
